create table queries (
	id INT,
	keyword VARCHAR(100),
	popularity INT,
	fullquery TEXT
);
insert into queries (id, keyword, popularity, fullquery) values (1, 'core', 86, 'justo in core blandit ultrices');
insert into queries (id, keyword, popularity, fullquery) values (2, 'Customer-focused', 52, 'Customer-focused vitae nisl');
insert into queries (id, keyword, popularity, fullquery) values (3, 'Function-based', 36, 'Function-based feugiat et eros vestibulum ac');
insert into queries (id, keyword, popularity, fullquery) values (4, 'User-centric', 75, 'User-centric vel augue vestibulum rutrum rutrum');
insert into queries (id, keyword, popularity, fullquery) values (5, 'bi-directional', 28, 'bi-directional enim');
insert into queries (id, keyword, popularity, fullquery) values (6, 'bandwidth-monitored', 57, 'bandwidth-monitored neque duis');
insert into queries (id, keyword, popularity, fullquery) values (7, 'task-force', 40, 'augue task-force vel');
insert into queries (id, keyword, popularity, fullquery) values (8, 'attitude', 61, 'attitude phasellus sit amet erat');
insert into queries (id, keyword, popularity, fullquery) values (9, 'national', 21, 'national et magnis dis parturient montes');
insert into queries (id, keyword, popularity, fullquery) values (10, 'global', 24, 'global orci luctus et ultrices');
insert into queries (id, keyword, popularity, fullquery) values (11, 'array', 58, 'array nullam varius nulla facilisi');
insert into queries (id, keyword, popularity, fullquery) values (12, 'knowledge user', 64, 'knowledge user condimentum curabitur in libero ut');
insert into queries (id, keyword, popularity, fullquery) values (13, 'artificial intelligence', 68, 'blandit artificial intelligence mi in');
insert into queries (id, keyword, popularity, fullquery) values (14, 'Object-based', 70, 'Object-based quam turpis adipiscing lorem');
insert into queries (id, keyword, popularity, fullquery) values (15, 'Organized', 28, 'Organized duis faucibus');
insert into queries (id, keyword, popularity, fullquery) values (16, 'Devolved', 28, 'Devolved suspendisse ornare consequat');
insert into queries (id, keyword, popularity, fullquery) values (17, 'archive', 51, 'aliquet archive  maecenas');
insert into queries (id, keyword, popularity, fullquery) values (18, 'matrices', 39, 'matrices cras pellentesque volutpat');
insert into queries (id, keyword, popularity, fullquery) values (19, 'Centralized', 50, 'Centralized nulla mollis molestie lorem');
insert into queries (id, keyword, popularity, fullquery) values (20, 'contextually-based', 2, 'contextually-based vestibulum sagittis sapien cum sociis');
insert into queries (id, keyword, popularity, fullquery) values (21, 'capability', 73, 'capability quis odio');
insert into queries (id, keyword, popularity, fullquery) values (22, 'access', 62, 'massa access id');
insert into queries (id, keyword, popularity, fullquery) values (23, 'fresh-thinking', 9, 'fresh-thinking vehicula condimentum curabitur');
insert into queries (id, keyword, popularity, fullquery) values (24, 'standardization', 77, 'standardization ante ipsum');
insert into queries (id, keyword, popularity, fullquery) values (25, 'Realigned', 65, 'Realigned nec nisi');
insert into queries (id, keyword, popularity, fullquery) values (26, 'architecture', 69, 'architecture curae donec pharetra magna');
insert into queries (id, keyword, popularity, fullquery) values (27, 'full-range', 86, 'full-range interdum mauris ullamcorper');
insert into queries (id, keyword, popularity, fullquery) values (28, '5th generation', 67, '5th generation dictumst morbi vestibulum');
insert into queries (id, keyword, popularity, fullquery) values (29, 'web-enabled', 88, 'web-enabled in faucibus orci luctus et');
insert into queries (id, keyword, popularity, fullquery) values (30, 'asymmetric', 98, 'asymmetric maecenas ut massa quis augue');
insert into queries (id, keyword, popularity, fullquery) values (31, 'leading edge', 86, 'leading edge blandit nam nulla integer');
insert into queries (id, keyword, popularity, fullquery) values (32, 'middleware', 95, 'middleware et ultrices');
insert into queries (id, keyword, popularity, fullquery) values (33, 'Automated', 74, 'Automated ultrices enim lorem');
insert into queries (id, keyword, popularity, fullquery) values (34, 'Versatile', 44, 'Versatile nunc donec');
insert into queries (id, keyword, popularity, fullquery) values (35, 'interface', 3, 'interface ac');
insert into queries (id, keyword, popularity, fullquery) values (36, 'superstructure', 90, 'superstructure a ipsum integer a');
insert into queries (id, keyword, popularity, fullquery) values (37, 'Fully-configurable', 97, 'Fully-configurable morbi vestibulum');
insert into queries (id, keyword, popularity, fullquery) values (38, 'Reactive', 12, 'Reactive rhoncus sed vestibulum sit');
insert into queries (id, keyword, popularity, fullquery) values (39, 'attitude', 55, 'attitude convallis nunc proin at');
insert into queries (id, keyword, popularity, fullquery) values (40, 'Graphic Interface', 69, 'Graphic Interface primis');
insert into queries (id, keyword, popularity, fullquery) values (41, 'uniform', 81, 'uniform luctus et ultrices posuere cubilia');
insert into queries (id, keyword, popularity, fullquery) values (42, 'concept', 100, 'concept amet consectetuer adipiscing');
insert into queries (id, keyword, popularity, fullquery) values (43, 'coherent', 12, 'coherent nam dui proin');
insert into queries (id, keyword, popularity, fullquery) values (44, 'open system', 52, 'open system molestie hendrerit at vulputate vitae');
insert into queries (id, keyword, popularity, fullquery) values (45, 'monitoring', 96, 'monitoring nunc rhoncus dui');
insert into queries (id, keyword, popularity, fullquery) values (46, 'function', 81, 'function quam pede lobortis ligula');
insert into queries (id, keyword, popularity, fullquery) values (47, 'national', 81, 'national adipiscing elit');
insert into queries (id, keyword, popularity, fullquery) values (48, 'Open-architected', 37, 'Open-architected duis ac nibh fusce');
insert into queries (id, keyword, popularity, fullquery) values (49, 'service-desk', 29, 'service-desk eu');
insert into queries (id, keyword, popularity, fullquery) values (50, 'matrices', 84, 'matrices integer tincidunt ante vel');
insert into queries (id, keyword, popularity, fullquery) values (51, 'high-level', 4, 'high-level sapien ut nunc');
insert into queries (id, keyword, popularity, fullquery) values (52, 'algorithm', 93, 'algorithm morbi');
insert into queries (id, keyword, popularity, fullquery) values (53, 'didactic', 27, 'didactic sem sed sagittis nam');
insert into queries (id, keyword, popularity, fullquery) values (54, 'optimizing', 8, 'optimizing vivamus vel nulla');
insert into queries (id, keyword, popularity, fullquery) values (55, 'task-force', 77, 'task-force cursus urna ut tellus');
insert into queries (id, keyword, popularity, fullquery) values (56, 'grid-enabled', 82, 'grid-enabled vestibulum quam sapien varius');
insert into queries (id, keyword, popularity, fullquery) values (57, 'Future-proofed', 36, 'Future-proofed penatibus et');
insert into queries (id, keyword, popularity, fullquery) values (58, 'high-level', 59, 'high-level felis');
insert into queries (id, keyword, popularity, fullquery) values (59, 'Re-contextualized', 79, 'Re-contextualized ut massa quis augue luctus');
insert into queries (id, keyword, popularity, fullquery) values (60, 'Proactive', 100, 'Proactive dapibus at');
insert into queries (id, keyword, popularity, fullquery) values (61, 'complexity', 80, 'complexity quam');
insert into queries (id, keyword, popularity, fullquery) values (62, 'Reactive', 58, 'Reactive lacus purus aliquet at');
insert into queries (id, keyword, popularity, fullquery) values (63, 'Persistent', 71, 'Persistent eu massa donec dapibus duis');
insert into queries (id, keyword, popularity, fullquery) values (64, 'systemic', 100, 'systemic porta volutpat erat quisque erat');
insert into queries (id, keyword, popularity, fullquery) values (65, 'Cross-platform', 68, 'Cross-platform at turpis donec posuere');
insert into queries (id, keyword, popularity, fullquery) values (66, 'Inverse', 52, 'Inverse aliquet at feugiat non pretium');
insert into queries (id, keyword, popularity, fullquery) values (67, 'migration', 48, 'migration morbi non quam nec dui');
insert into queries (id, keyword, popularity, fullquery) values (68, 'uniform', 14, 'uniform cubilia curae mauris viverra');
insert into queries (id, keyword, popularity, fullquery) values (69, 'homogeneous', 13, 'homogeneous nunc');
insert into queries (id, keyword, popularity, fullquery) values (70, 'access', 75, 'access eget');
insert into queries (id, keyword, popularity, fullquery) values (71, 'Programmable', 27, 'Programmable nibh in');
insert into queries (id, keyword, popularity, fullquery) values (72, 'complexity', 45, 'complexity ultrices');
insert into queries (id, keyword, popularity, fullquery) values (73, 'customer loyalty', 23, 'customer loyalty nam ultrices libero');
insert into queries (id, keyword, popularity, fullquery) values (74, 'Distributed', 4, 'Distributed posuere nonummy integer');
insert into queries (id, keyword, popularity, fullquery) values (75, 'extranet', 45, 'extranet turpis');
insert into queries (id, keyword, popularity, fullquery) values (76, 'non-volatile', 47, 'non-volatile sapien placerat ante');
insert into queries (id, keyword, popularity, fullquery) values (77, 'concept', 97, 'concept leo pellentesque ultrices');
insert into queries (id, keyword, popularity, fullquery) values (78, 'cohesive', 3, 'cohesive nec nisi volutpat');
insert into queries (id, keyword, popularity, fullquery) values (79, '5th generation', 38, '5th generation orci luctus et ultrices');
insert into queries (id, keyword, popularity, fullquery) values (80, 'installation', 98, 'installation erat curabitur gravida nisi');
insert into queries (id, keyword, popularity, fullquery) values (81, 'Proactive', 45, 'Proactive ligula');
insert into queries (id, keyword, popularity, fullquery) values (82, 'architecture', 35, 'architecture vestibulum sed magna at nunc');
insert into queries (id, keyword, popularity, fullquery) values (83, 'Persistent', 38, 'Persistent vitae');
insert into queries (id, keyword, popularity, fullquery) values (84, 'Team-oriented', 20, 'Team-oriented eget massa tempor convallis nulla');
insert into queries (id, keyword, popularity, fullquery) values (85, 'moderator', 9, 'moderator venenatis');
insert into queries (id, keyword, popularity, fullquery) values (86, 'value-added', 17, 'value-added ipsum ac tellus semper');
insert into queries (id, keyword, popularity, fullquery) values (87, 'paradigm', 25, 'paradigm sodales');
insert into queries (id, keyword, popularity, fullquery) values (88, 'Triple-buffered', 91, 'Triple-buffered sed');
insert into queries (id, keyword, popularity, fullquery) values (89, 'Streamlined', 28, 'Streamlined praesent');
insert into queries (id, keyword, popularity, fullquery) values (90, 'database', 96, 'database tincidunt eu felis fusce posuere');
insert into queries (id, keyword, popularity, fullquery) values (91, 'Versatile', 26, 'Versatile viverra eget congue eget');
insert into queries (id, keyword, popularity, fullquery) values (92, 'modular', 61, 'modular nec nisi volutpat');
insert into queries (id, keyword, popularity, fullquery) values (93, 'Streamlined', 95, 'Streamlined quis turpis eget');
insert into queries (id, keyword, popularity, fullquery) values (94, 'extranet', 65, 'extranet vel nulla eget eros elementum');
insert into queries (id, keyword, popularity, fullquery) values (95, 'Managed', 31, 'Managed duis mattis egestas');
insert into queries (id, keyword, popularity, fullquery) values (96, 'Ergonomic', 48, 'Ergonomic lacus curabitur at');
insert into queries (id, keyword, popularity, fullquery) values (97, 'artificial intelligence', 8, 'artificial intelligence tincidunt lacus at');
insert into queries (id, keyword, popularity, fullquery) values (98, 'Cloned', 62, 'Cloned aenean auctor gravida sem praesent');
insert into queries (id, keyword, popularity, fullquery) values (99, 'definition', 65, 'definition posuere metus');
insert into queries (id, keyword, popularity, fullquery) values (100, 'matrices', 42, 'matrices erat curabitur gravida nisi at');
